name: eng_gruposbf_mobile_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter_localizations:
      sdk: flutter
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  build_runner: 2.3.3
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^5.0.3
  get: ^4.6.5
  skeleton_text: ^3.0.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/